### ISSUE TITLE
RuntimeException: Case mismatch between loaded and declared class names

### ISSUE THREAD

**Issue by ccMatrix** [liuggio/StatsDClientBundle#47]
Last update from 1.6.5 to 1.6.6 added the following line to services.yml:

```yml
liuggio_stats_d.sender.class: Liuggio\StatsdClient\Service\StatsdService
```

This throws a RuntimeException since: Case mismatch between loaded and declared class names: Liuggio\StatsdClient\Service\StatsdService vs Liuggio\StatsdClient\Service\StatsDService

Updating the line with uppercase D fixes the issue:

```yml
liuggio_stats_d.sender.class: Liuggio\StatsdClient\Service\StatsDService
```

**Comment by liuggio** [comment]
can you provide a PR?

**Comment by liuggio** [comment]
Thanks a lot for the feedback :dancers:
