### ISSUE TITLE
hostedgraphite.com data not shown 

### ISSUE THREAD

**Issue by grekpg** [liuggio/StatsDClientBundle#49]
I try test this service (https://www.hostedgraphite.com StatsD and Graphite online ) with StatsDClientBundle.

They need add id to surfix of message - i try like this 

$this->get('statsd')->set($myId'.test',25); 

any error but data is not collect in hostedgraphite.

**Comment by liuggio** [comment]
Hi thanks for reporting, 
the example you provided is not correct
`$this->get('statsd')->gauge($myId.'.test',25);`

Or maybe the port/host configured correctly?
`conn = fsockopen("carbon.hostedgraphite.com", 2003);`

**Comment by grekpg** [comment]
port and host is ok - 
liuggio_stats_d_client:
  connection:
    host: carbon.hostedgraphite.com
    port: 2003

when i send 
$this->get('statsd')->gauge($myId.'.test',25); 
i see in SocketSender write method : 

$message = e9f3c189-3c9f-4c6a-8560-fe2bbce79bcb.test:25|g

this is correct ? 

in http://docs.hostedgraphite.com/languageguide/lg_php.html i see message like here $message = "YOUR-API-KEY.foo 1.2\n";

**Comment by grekpg** [comment]
why you close it ?

**Comment by liuggio** [comment]
I think that this is not related to this project, if yes I'll be happy to re-open again

**Comment by dav-m85** [comment]
Seems you are not flushing it:
```php
$this->get('statsd')->gauge($myId.'.test',25)->flush(); 
```

Hopes it is not too late.
