### ISSUE TITLE
On dev env the data are not pushed to the socket

### ISSUE THREAD

**Issue by grekpg** [liuggio/StatsDClientBundle#50]
How to enable sending data in dev mode ?

**Comment by liuggio** [comment]
Hi
try use `debug:false` inside the `connection` section in this bundle config :)
( https://github.com/liuggio/StatsDClientBundle/blob/7ea0873c8f788192d5693b5381149ac99a43b8fe/DependencyInjection/Configuration.php#L36 )

hope this help
