### ISSUE TITLE
Timers in DbalStatsCollector

### ISSUE THREAD

**Issue by seisler** [liuggio/StatsDClientBundle#53]
Hi, great work!

I cannot see the time that spends every query in the syslog file. Is the collector already getting the time? or I have to implement more logic? 

Thanks

**Comment by liuggio** [comment]
@seisler you are talking about the doctrine integration?

**Comment by seisler** [comment]
I read that SQLLogger logs all the sql data included the time that spends the query. I'm interested to send to graphite the time that spends the queries in my app and I thought that the DbalStatsCollector can do it. I'm interested in collectors and I was wondering if I can use this collector or I will have to write my own collector. 

Thanks

**Comment by liuggio** [comment]
would be a good feature :)

**Comment by seisler** [comment]
I close the issue. the v2.0.0 will have the adrienbrault collectors. And there is a collector that save the timing of the queries. 

Thanks and sorry. :)
