### ISSUE TITLE
Create new collector does not work

### ISSUE THREAD

**Issue by seisler** [liuggio/StatsDClientBundle#54]
Hi. 

I have a problem adding a new Collector. I followed the documentation part: https://github.com/liuggio/StatsDClientBundle/blob/master/Resources/doc/advanced.md

I want to create another dbal collector. I copied the same structure as you have for that collector. I created the service just like you. I added the reference to the service in the config. But nothing happens. All the collectors are working perfectly but mine. It seems like my collector is not registered.

pd: the collector code works. I put it on your dbal collector and it's working. 

Some help would be great.

Thanks

**Comment by liuggio** [comment]
did you also add to the parameter?
https://github.com/liuggio/StatsDClientBundle/blob/master/DependencyInjection/Compiler/CollectorCompilerPass.php#L23

**Comment by seisler** [comment]
Ok. I found the problem. I created my dbal collector and I called it 'mybundle.collector.dbal' and in your CollectorCompilerPass you only attach the collector to the dbal sql logger chain if $id === 'liuggio_stats_d_client.collector.dbal'.

So. It would be great if the id could be more flexible.

Thanks for all. :)
