### ISSUE TITLE
Deprecated security.context

### ISSUE THREAD

**Issue by alinilie** [liuggio/StatsDClientBundle#61]
Hi,

I use "liuggio/statsd-client-bundle": "v1.6.9" in Symfony 2.8.3 and I get an deprecated message from this line: [StatsDClientBundle/Resources/config/collectors.yml#27](https://github.com/liuggio/StatsDClientBundle/blob/master/Resources/config/collectors.yml#L27):

 _The "security.context" service is deprecated since Symfony 2.6 and will be removed in 3.0._

Thanks!

**Comment by liuggio** [comment]
Great! Would you like to provide a PR?

**Comment by alinilie** [comment]
I could provide a PR for this issue, but this will increase the dependency to Symfony >=2.6. Are you ok with that?

**Comment by liuggio** [comment]
@alinilie   would be awesome

**Comment by garak** [comment]
Fixed
