### ISSUE TITLE
Remove classnames parameters

### ISSUE THREAD

**Issue by garak** [liuggio/StatsDClientBundle#68]
Parameters for classname are an heritage of old times in Symfony.
We should get rid of them and declare classnames directly in service definitions

**Comment by jatempa** [comment]
I want to work on this, please can you tell me what are the classes?

**Comment by ClementGautier** [comment]
Each year I'll come to haunt you on this issue like a :ghost: for Halloween. Do you still need this to be fixed?

**Comment by garak** [comment]
@ClementGautier https://github.com/liuggio/StatsDClientBundle/blob/master/Resources/config/collectors.yml#L1 etc.
Happy Halloween! 🎃
