### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by garak** [liuggio/StatsDClientBundle#69]
We miss it!
See https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by code4t2** [comment]
Hello! Could I take a shot at this?

If yes, would you like your CONTRIBUTING.md in a docs directory or at the project root?
Also, would you like the same material from your [Contribution section in your README.md](https://github.com/liuggio/StatsDClientBundle#contribution) or would you like any extra material added in?

**Comment by code4t2** [comment]
Never mind! Seems to have a relevant pull request already
